class Error(Exception):
    def print_error(self) -> None:
        pass
